version: "3"
services:
  PROJECT_NAME:
    image: AWS_ID.dkr.ecr.AWS_REGION.amazonaws.com/AWS_IMAGE_REGISTRY:STAGE
    restart: always
    container_name: "PROJECT_NAME"
    env_file:
      - .env
    command: "npm run STAGE"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.PROJECT_NAME-http.rule=(`WEBITE_URL`)"
      - "traefik.http.routers.PROJECT_NAME-http.entrypoints=http"
      - "traefik.http.routers.PROJECT_NAME-http.middlewares=https-redirect@file"
      - "traefik.http.routers.PROJECT_NAME-https.rule=Host(`WEBITE_URL`)"
      - "traefik.http.routers.PROJECT_NAME-https.entrypoints=https"
      - "traefik.http.routers.PROJECT_NAME-https.middlewares=security@file, compression@file"
      - "traefik.http.routers.PROJECT_NAME-https.tls=true"
      - "traefik.http.routers.PROJECT_NAME-https.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
